<?php

namespace FactelBundle\Entity;

/**
 * TipocuentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipocuentaRepository extends \Doctrine\ORM\EntityRepository
{
}
